GET http://127.0.0.1:8000/v1/wx/video-info?url=https://video.weibo.com/show?fid=1034:4808962013593712
Accept: application/json

###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/login
Accept: application/json

###
