GET http://127.0.0.1:8000/v1/wx/video-info?url=https%3A//isee.weishi.qq.com/ws/app-pages/share/index.html%3Fwxplay%3D1%26id%3D6Zo3BXMgn1NzzsMC8%26spid%3D3599431994062053125%26qua%3Dv1_iph_weishi_8.79.0_209_app_a%26chid%3D100081014%26pkg%3D3670%26attach%3Dcp_reserves3_1000370011
Accept: application/json

###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/login
Accept: application/json

###
